version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
    overwrite: yes

permissions:
  - object: /home/ubuntu
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/shutdown-prev-application.sh
      timeout: 120
      runas: ubuntu

  ApplicationStart:
    - location: scripts/build-and-run-new-application.sh
      timeout: 120
      runas: ubuntu
