version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
    overwrite: yes

permissions:
  - object: /home/ubuntu
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/shutdown-prev-application.sh
      runas: ubuntu

  AfterInstall:
    - location: scripts/build-and-run-new-application.sh
      runas: ubuntu
