name: run test

on:
  pull_request:
    branches: [main, dev]
    types: [opened, synchronize, reopened]

permissions:
  checks: write
  pull-requests: write

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: 체크아웃
        uses: actions/checkout@v4

      - name: JDK 11 설치
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '11'
          cache: 'gradle'

      - name: Gradle에 실행 권한 부여
        run: chmod +x gradlew

      - name: Test 실행
        run: ./gradlew clean test

      - name: Test 결과를 PR에 코멘트로 등록
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: '**/build/test-results/test/TEST-*.xml'
